// Defines reusable ReAct state and report types shared by authored agent
// surfaces without introducing a second execution runtime.
#pragma once

#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

#include "wh/agent/agent.hpp"
#include "wh/agent/instruction.hpp"
#include "wh/agent/toolset.hpp"
#include "wh/compose/node/component.hpp"
#include "wh/compose/node/tools_contract.hpp"
#include "wh/core/any.hpp"
#include "wh/core/error.hpp"
#include "wh/core/result.hpp"
#include "wh/model/chat_model.hpp"
#include "wh/schema/message.hpp"

namespace wh::agent {

/// Stable internal key used for the authored ReAct model node.
inline constexpr std::string_view react_model_node_key = "__react_model__";

/// Final-output storage mode used by chat-model agents.
enum class react_output_mode {
  /// Store the final assistant or tool message value under the configured
  /// output key.
  value = 0U,
  /// Store the final rendered text under the configured output key.
  stream,
};

/// One tool action generated by the current assistant turn.
struct react_tool_action {
  /// Stable tool-call id emitted by the model.
  std::string call_id{};
  /// Tool name selected by the model.
  std::string tool_name{};
  /// Structured tool arguments payload passed through the tool boundary.
  std::string arguments{};
  /// True marks this concrete tool call as return-direct candidate.
  bool return_direct{false};
};

/// One full model or tool round recorded by the agent loop.
struct react_round_record {
  /// Assistant message produced by the model for this round.
  wh::schema::message assistant_message{};
  /// Tool actions extracted from the assistant message.
  std::vector<react_tool_action> tool_actions{};
  /// Tool results observed after dispatching this round's actions.
  std::vector<wh::compose::tool_result> tool_results{};
};

/// Mutable ReAct state that can be checkpointed or resumed explicitly by value.
struct react_state {
  /// Full authored conversation history, including tool-result messages.
  std::vector<wh::schema::message> messages{};
  /// Remaining model iterations allowed before the loop must stop.
  std::size_t remaining_iterations{0U};
  /// Pending tool actions restored before the next tool-dispatch step.
  std::vector<react_tool_action> pending_tool_actions{};
  /// Return-direct tool-call id that terminated the run, when any.
  std::optional<std::string> return_direct_call_id{};
  /// Optional output slot written when the run finishes successfully.
  std::unordered_map<std::string, wh::core::any,
                     wh::core::transparent_string_hash,
                     wh::core::transparent_string_equal>
      output_values{};
};

/// Immutable execution report emitted after one chat-model-agent run.
struct react_report {
  /// Ordered round trace captured during this run.
  std::vector<react_round_record> rounds{};
  /// Final message emitted to the caller when the run completed successfully.
  std::optional<wh::schema::message> final_message{};
  /// Final rendered text emitted to the caller when text output is requested.
  std::optional<std::string> final_text{};
  /// Return-direct tool-call id that terminated the run, when any.
  std::optional<std::string> return_direct_call_id{};
  /// Terminal error observed by the loop, when the run failed before
  /// completion.
  std::optional<wh::core::error_code> final_error{};
  /// True once the loop emitted a terminal success path.
  bool completed{false};
};

/// Thin authored ReAct shell that captures prompt, toolset, and loop policy
/// without embedding execution or transport logic.
class react {
public:
  /// Creates one authored ReAct shell from the required name and description.
  react(std::string name, std::string description) noexcept
      : name_(std::move(name)), description_(std::move(description)) {}

  react(const react &) = delete;
  auto operator=(const react &) -> react & = delete;
  react(react &&) noexcept = default;
  auto operator=(react &&) noexcept -> react & = default;
  ~react() = default;

  /// Returns the authored shell name.
  [[nodiscard]] auto name() const noexcept -> std::string_view { return name_; }

  /// Returns the authored shell description.
  [[nodiscard]] auto description() const noexcept -> std::string_view {
    return description_;
  }

  /// Returns true after authoring has been frozen successfully.
  [[nodiscard]] auto frozen() const noexcept -> bool { return frozen_; }

  /// Appends one instruction fragment before freeze.
  auto append_instruction(std::string text, const std::int32_t priority = 0)
      -> wh::core::result<void> {
    auto mutable_status = ensure_mutable();
    if (mutable_status.has_error()) {
      return mutable_status;
    }
    instruction_.append(std::move(text), priority);
    return {};
  }

  /// Replaces the current base instruction before freeze.
  auto replace_instruction(std::string text, const std::int32_t priority = 0)
      -> wh::core::result<void> {
    auto mutable_status = ensure_mutable();
    if (mutable_status.has_error()) {
      return mutable_status;
    }
    instruction_.replace(std::move(text), priority);
    return {};
  }

  /// Renders the authored instruction string.
  [[nodiscard]] auto
  render_instruction(const std::string_view separator = "\n") const
      -> std::string {
    return instruction_.render(separator);
  }

  /// Registers one raw compose tool entry before freeze.
  auto add_tool_entry(wh::schema::tool_schema_definition schema,
                      wh::compose::tool_entry entry,
                      const wh::agent::tool_registration registration = {})
      -> wh::core::result<void> {
    auto mutable_status = ensure_mutable();
    if (mutable_status.has_error()) {
      return mutable_status;
    }
    return tools_.add_entry(std::move(schema), std::move(entry), registration);
  }

  /// Registers one executable tool component before freeze.
  template <wh::agent::detail::registered_tool_component tool_t>
  auto add_tool(const tool_t &tool,
                const wh::agent::tool_registration registration = {})
      -> wh::core::result<void> {
    auto mutable_status = ensure_mutable();
    if (mutable_status.has_error()) {
      return mutable_status;
    }
    return tools_.add_tool(tool, registration);
  }

  /// Appends one shared tool middleware layer before freeze.
  auto add_tool_middleware(wh::compose::tool_middleware middleware)
      -> wh::core::result<void> {
    auto mutable_status = ensure_mutable();
    if (mutable_status.has_error()) {
      return mutable_status;
    }
    return tools_.add_middleware(std::move(middleware));
  }

  /// Pins the authored tools-node lowering options used by the shell.
  auto set_tools_node_options(const tools_node_authoring_options options)
      -> wh::core::result<void> {
    auto mutable_status = ensure_mutable();
    if (mutable_status.has_error()) {
      return mutable_status;
    }
    return tools_.set_node_options(options);
  }

  /// Replaces the maximum loop iterations. Zero falls back to one.
  auto set_max_iterations(const std::size_t max_iterations)
      -> wh::core::result<void> {
    auto mutable_status = ensure_mutable();
    if (mutable_status.has_error()) {
      return mutable_status;
    }
    max_iterations_ = max_iterations == 0U ? 1U : max_iterations;
    return {};
  }

  /// Sets the optional output slot name written at graph exit.
  auto set_output_key(std::string output_key) -> wh::core::result<void> {
    auto mutable_status = ensure_mutable();
    if (mutable_status.has_error()) {
      return mutable_status;
    }
    output_key_ = std::move(output_key);
    return {};
  }

  /// Selects how the configured output slot is materialized.
  auto set_output_mode(const react_output_mode mode) -> wh::core::result<void> {
    auto mutable_status = ensure_mutable();
    if (mutable_status.has_error()) {
      return mutable_status;
    }
    output_mode_ = mode;
    return {};
  }

  template <wh::model::chat_model_like model_t>
  /// Installs the chat-model leaf component used by this ReAct shell.
  auto set_model(model_t &&model) -> wh::core::result<void> {
    auto mutable_status = ensure_mutable();
    if (mutable_status.has_error()) {
      return mutable_status;
    }
    model_node_.emplace(
        wh::compose::make_component_node<wh::compose::component_kind::model,
                                         wh::compose::node_contract::value,
                                         wh::compose::node_contract::stream>(
            react_model_node_key, std::forward<model_t>(model)));
    return {};
  }

  /// Returns the frozen toolset surface.
  [[nodiscard]] auto tools() const noexcept -> const wh::agent::toolset & {
    return tools_;
  }

  /// Returns the frozen model node used by this shell.
  [[nodiscard]] auto model_node() const -> wh::core::result<
      std::reference_wrapper<const wh::compose::component_node>> {
    if (!model_node_.has_value()) {
      return wh::core::result<
          std::reference_wrapper<const wh::compose::component_node>>::
          failure(wh::core::errc::not_found);
    }
    return std::cref(*model_node_);
  }

  /// Returns the configured maximum iterations.
  [[nodiscard]] auto max_iterations() const noexcept -> std::size_t {
    return max_iterations_;
  }

  /// Returns the configured output slot name.
  [[nodiscard]] auto output_key() const noexcept -> std::string_view {
    return output_key_;
  }

  /// Returns the configured output materialization mode.
  [[nodiscard]] auto output_mode() const noexcept -> react_output_mode {
    return output_mode_;
  }

  /// Converts this frozen authored shell into the common executable agent surface.
  [[nodiscard]] auto into_agent() && -> wh::core::result<wh::agent::agent>;

  /// Validates authored configuration and freezes this shell once.
  auto freeze() -> wh::core::result<void> {
    if (frozen_) {
      return {};
    }
    if (name_.empty() || description_.empty()) {
      return wh::core::result<void>::failure(wh::core::errc::invalid_argument);
    }
    if (!model_node_.has_value()) {
      return wh::core::result<void>::failure(wh::core::errc::not_found);
    }
    if (max_iterations_ == 0U) {
      return wh::core::result<void>::failure(wh::core::errc::invalid_argument);
    }
    if (!tools_.node_options().has_value()) {
      return wh::core::result<void>::failure(
          wh::core::errc::contract_violation);
    }
    frozen_ = true;
    return {};
  }

private:
  [[nodiscard]] auto ensure_mutable() const -> wh::core::result<void> {
    if (frozen_) {
      return wh::core::result<void>::failure(
          wh::core::errc::contract_violation);
    }
    return {};
  }

  std::string name_{};
  std::string description_{};
  wh::agent::instruction instruction_{};
  std::optional<wh::compose::component_node> model_node_{};
  wh::agent::toolset tools_{};
  std::size_t max_iterations_{20U};
  std::string output_key_{};
  react_output_mode output_mode_{react_output_mode::value};
  bool frozen_{false};
};

/// Rewrites one assistant or tool history message into a neutral context prompt
/// so downstream agents do not treat it as a fresh direct conversation turn.
[[nodiscard]] inline auto
rewrite_history_message_as_context_prompt(const wh::schema::message &message)
    -> std::optional<wh::schema::message> {
  if (message.role != wh::schema::message_role::assistant &&
      message.role != wh::schema::message_role::tool) {
    return message;
  }

  std::string text{"For context:"};
  bool wrote_context = false;
  if (message.role == wh::schema::message_role::assistant) {
    std::string rendered{};
    for (const auto &part : message.parts) {
      if (const auto *typed = std::get_if<wh::schema::text_part>(&part);
          typed != nullptr) {
        rendered.append(typed->text);
      }
    }
    if (!rendered.empty()) {
      text.append(" assistant said: ");
      text.append(rendered);
      text.push_back('.');
      wrote_context = true;
    }
    for (const auto &part : message.parts) {
      const auto *tool = std::get_if<wh::schema::tool_call_part>(&part);
      if (tool == nullptr) {
        continue;
      }
      text.append(" assistant called tool `");
      text.append(tool->name);
      text.append("` with arguments: ");
      text.append(tool->arguments);
      text.push_back('.');
      wrote_context = true;
    }
  } else {
    std::string rendered{};
    for (const auto &part : message.parts) {
      if (const auto *typed = std::get_if<wh::schema::text_part>(&part);
          typed != nullptr) {
        rendered.append(typed->text);
      }
    }
    if (!rendered.empty()) {
      text.append(" tool");
      if (!message.tool_name.empty()) {
        text.append(" `");
        text.append(message.tool_name);
        text.push_back('`');
      }
      text.append(" returned result: ");
      text.append(rendered);
      text.push_back('.');
      wrote_context = true;
    }
  }

  if (!wrote_context) {
    return std::nullopt;
  }

  wh::schema::message rewritten{};
  rewritten.role = wh::schema::message_role::user;
  rewritten.parts.emplace_back(wh::schema::text_part{std::move(text)});
  return rewritten;
}

} // namespace wh::agent
