// Defines reusable ReAct state and report types shared by authored agent
// wrappers without introducing a second execution runtime.
#pragma once

#include <optional>
#include <span>
#include <string>
#include <unordered_map>
#include <vector>

#include "wh/compose/node/tools_contract.hpp"
#include "wh/core/any.hpp"
#include "wh/core/error.hpp"
#include "wh/schema/message.hpp"

namespace wh::agent {

/// Final-output storage mode used by chat-model agents.
enum class react_output_mode {
  /// Store the final assistant/tool message value under the configured output key.
  value = 0U,
  /// Store the final rendered text under the configured output key.
  stream,
};

/// One tool action generated by the current assistant turn.
struct react_tool_action {
  /// Stable tool-call id emitted by the model.
  std::string call_id{};
  /// Tool name selected by the model.
  std::string tool_name{};
  /// Structured tool arguments payload passed through the tool boundary.
  std::string arguments{};
  /// True marks this concrete tool call as return-direct candidate.
  bool return_direct{false};
};

/// One full model/tool round recorded by the agent loop.
struct react_round_record {
  /// Assistant message produced by the model for this round.
  wh::schema::message assistant_message{};
  /// Tool actions extracted from the assistant message.
  std::vector<react_tool_action> tool_actions{};
  /// Tool results observed after dispatching this round's actions.
  std::vector<wh::compose::tool_result> tool_results{};
};

/// Mutable ReAct state that can be checkpointed or resumed explicitly by value.
struct react_state {
  /// Full authored conversation history, including tool-result messages.
  std::vector<wh::schema::message> messages{};
  /// Remaining model iterations allowed before the loop must stop.
  std::size_t remaining_iterations{0U};
  /// Pending tool actions restored before the next tool-dispatch step.
  std::vector<react_tool_action> pending_tool_actions{};
  /// Return-direct tool-call id that terminated the run, when any.
  std::optional<std::string> return_direct_call_id{};
  /// Optional output slot written when the run finishes successfully.
  std::unordered_map<std::string, wh::core::any, wh::core::transparent_string_hash,
                     wh::core::transparent_string_equal>
      output_values{};
};

/// Immutable execution report emitted after one chat-model-agent run.
struct react_report {
  /// Ordered round trace captured during this run.
  std::vector<react_round_record> rounds{};
  /// Final message emitted to the caller when the run completed successfully.
  std::optional<wh::schema::message> final_message{};
  /// Final rendered text emitted to the caller when text output is requested.
  std::optional<std::string> final_text{};
  /// Return-direct tool-call id that terminated the run, when any.
  std::optional<std::string> return_direct_call_id{};
  /// Terminal error observed by the loop, when the run failed before completion.
  std::optional<wh::core::error_code> final_error{};
  /// True once the loop emitted a terminal success path.
  bool completed{false};
};

} // namespace wh::agent
