// Defines shared compose node execution primitives used by compiled/runtime paths.
#pragma once

#include <exec/any_sender_of.hpp>
#include <stdexec/execution.hpp>

#include <concepts>
#include <cstddef>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>

#include "wh/compose/graph/stream.hpp"
#include "wh/compose/graph/call_options.hpp"
#include "wh/compose/node/path.hpp"
#include "wh/compose/runtime/state.hpp"
#include "wh/compose/types.hpp"
#include "wh/core/function.hpp"
#include "wh/core/run_context.hpp"
#include "wh/core/stdexec.hpp"

namespace wh::compose {

class graph;
namespace detail::runtime_state {
struct invoke_outputs;
}

/// Per-node trace payload generated by graph runtime for one execution attempt.
struct graph_node_trace {
  /// Distributed trace id shared by the whole invoke run.
  std::string_view trace_id{};
  /// Span id unique to this concrete node execution attempt.
  std::string span_id{};
  /// Parent span id for this node execution.
  std::string parent_span_id{};
  /// Full runtime node path emitted into callback metadata.
  const wh::core::address *path{nullptr};
};

/// Type-erased async result boundary used by compiled compose runtime.
using graph_sender = graph_value_sender;

template <typename result_t>
using typed_result_sender = typename exec::any_receiver_ref<
    stdexec::completion_signatures<stdexec::set_value_t(result_t),
                                   stdexec::set_stopped_t()>>::
    template any_sender<>;

namespace detail {
[[nodiscard]] inline auto
failure_graph_sender(const wh::core::error_code code) -> graph_sender;
}

/// Type-erased nested-graph bridge used only inside graph runtime.
struct nested_graph_entry {
  using start_fn = graph_sender (*)(
      const void *, const graph &, wh::core::run_context &, graph_value &,
      const graph_call_scope *, const node_path *, graph_process_state *,
      detail::runtime_state::invoke_outputs *, const graph_node_trace *);

  const void *state{nullptr};
  start_fn start{nullptr};

  [[nodiscard]] auto bound() const noexcept -> bool {
    return state != nullptr && start != nullptr;
  }

  [[nodiscard]] auto operator()(const graph &target,
                                wh::core::run_context &context,
                                graph_value &input,
                                const graph_call_scope *call_options,
                                const node_path *path_prefix,
                                graph_process_state *parent_process_state,
                                detail::runtime_state::invoke_outputs *nested_outputs,
                                const graph_node_trace *parent_trace) const
    -> graph_sender {
    if (!bound()) {
      return detail::failure_graph_sender(wh::core::errc::contract_violation);
    }
    return start(state, target, context, input, call_options, path_prefix,
                 parent_process_state, nested_outputs, parent_trace);
  }
};

/// Runtime-only execution context passed from graph engine to each node run.
struct node_runtime {
  std::size_t parallel_gate{0U};
  const graph_call_scope *call_options{nullptr};
  const node_path *path{nullptr};
  graph_process_state *local_process_state{nullptr};
  const graph_component_option_map *component_options{nullptr};
  const graph_resolved_node_observation *observation{nullptr};
  const graph_node_trace *trace{nullptr};
  detail::runtime_state::invoke_outputs *invoke_outputs{nullptr};
  nested_graph_entry nested_entry{};
};

/// Type-erased sync callback used by compiled graph runtime.
using node_sync_factory = wh::core::callback_function<
    wh::core::result<graph_value>(graph_value &, wh::core::run_context &,
                                  const node_runtime &) const>;
/// Type-erased async callback used by compiled graph runtime.
using node_async_factory = wh::core::callback_function<
    graph_sender(graph_value &, wh::core::run_context &,
                 const node_runtime &) const>;

template <typename sender_t, typename result_t>
struct result_value_signature : std::false_type {};

template <typename result_t, typename... signatures_t>
struct result_value_signature<result_t,
                              stdexec::completion_signatures<signatures_t...>>
    : std::bool_constant<
          stdexec::completion_signatures<signatures_t...>::__count(
              stdexec::set_value) == 1U &&
          stdexec::completion_signatures<
              signatures_t...>::template __contains<stdexec::set_value_t(
              result_t)>()> {};

template <typename sender_t, typename result_t>
concept result_typed_sender =
    stdexec::sender<std::remove_cvref_t<sender_t>> &&
    result_value_signature<
        result_t,
        stdexec::completion_signatures_of_t<std::remove_cvref_t<sender_t>,
                                            stdexec::env<>>>::value;

template <typename sender_t>
concept graph_result_sender = result_typed_sender<
    sender_t, wh::core::result<graph_value>>;
template <typename sender_t>
concept graph_stream_result_sender = result_typed_sender<
    sender_t, wh::core::result<graph_stream_reader>>;
template <typename sender_t>
concept graph_map_result_sender = result_typed_sender<
    sender_t, wh::core::result<graph_value_map>>;

template <typename run_t>
concept node_sync_run =
    requires(run_t run, graph_value &input, wh::core::run_context &context,
             const node_runtime &runtime) {
      { run(input, context, runtime) }
      -> std::same_as<wh::core::result<graph_value>>;
    };

template <typename run_t>
concept node_async_run =
    requires(run_t run, graph_value &input,
             wh::core::run_context &context,
             const node_runtime &runtime) {
      { run(input, context, runtime) } -> graph_result_sender;
    };

namespace detail {

template <typename value_t> struct mutable_capture {
  mutable value_t value;
};

template <typename value_t>
[[nodiscard]] constexpr auto make_mutable_capture(value_t &&value)
    -> mutable_capture<std::decay_t<value_t>> {
  return mutable_capture<std::decay_t<value_t>>{
      std::forward<value_t>(value)};
}

[[nodiscard]] inline auto normalize_graph_sender(graph_sender sender)
    -> graph_sender {
  return sender;
}

template <stdexec::sender sender_t>
[[nodiscard]] inline auto normalize_graph_sender(sender_t &&sender) {
  return wh::core::detail::normalize_result_sender<wh::core::result<graph_value>>(
      std::forward<sender_t>(sender));
}

[[nodiscard]] inline auto
failure_graph_sender(const wh::core::error_code code) -> graph_sender {
  return graph_sender{
      wh::core::detail::failure_result_sender<wh::core::result<graph_value>>(
          code)};
}

[[nodiscard]] inline auto
ready_graph_sender(wh::core::result<graph_value> status) -> graph_sender {
  return graph_sender{wh::core::detail::ready_sender(std::move(status))};
}

[[nodiscard]] inline auto bridge_graph_sender(graph_sender sender)
    -> graph_sender {
  return sender;
}

template <stdexec::sender sender_t>
[[nodiscard]] inline auto bridge_graph_sender(sender_t &&sender) -> graph_sender {
  return graph_sender{normalize_graph_sender(std::forward<sender_t>(sender))};
}

template <stdexec::sender sender_t, typename mapper_t>
[[nodiscard]] inline auto map_graph_sender(sender_t &&sender, mapper_t &&mapper)
    -> graph_sender {
  return bridge_graph_sender(
      wh::core::detail::map_result_sender<wh::core::result<graph_value>>(
          std::forward<sender_t>(sender), std::forward<mapper_t>(mapper)));
}

template <node_sync_run run_t>
[[nodiscard]] inline auto bind_node_sync_factory(run_t &&run)
    -> node_sync_factory {
  auto stored = make_mutable_capture(std::forward<run_t>(run));
  return node_sync_factory{
      [stored = std::move(stored)](graph_value &input,
                                   wh::core::run_context &context,
                                   const node_runtime &runtime)
          -> wh::core::result<graph_value> {
        return stored.value(input, context, runtime);
      }};
}

template <node_async_run run_t>
[[nodiscard]] inline auto bind_node_async_factory(run_t &&run)
    -> node_async_factory {
  auto stored = make_mutable_capture(std::forward<run_t>(run));
  return node_async_factory{
      [stored = std::move(stored)](graph_value &input,
                                   wh::core::run_context &context,
                                   const node_runtime &runtime)
          -> graph_sender {
        return bridge_graph_sender(stored.value(input, context, runtime));
      }};
}

template <graph_result_sender sender_t>
[[nodiscard]] inline auto bind_node_async_factory(sender_t &&sender)
    -> node_async_factory {
  using stored_sender_t = std::decay_t<sender_t>;
  static_assert(std::copy_constructible<stored_sender_t>,
                "direct sender node requires copyable sender; "
                "use sender-factory lambda for move-only senders");
  auto stored = make_mutable_capture(std::forward<sender_t>(sender));
  return node_async_factory{
      [stored = std::move(stored)](graph_value &,
                                   wh::core::run_context &,
                                   const node_runtime &) -> graph_sender {
        return bridge_graph_sender(stored.value);
      }};
}

} // namespace detail

} // namespace wh::compose
